### ISSUE TITLE
guess something broken

### ISSUE THREAD

**Issue by nikitasius** [sponnet/locals-faucetserver#14]
Hi, guess something is broken.

I requested payments, got feedback but received nothing.

* `0xee168726d52313651aee118a2b4416ece521e8cc` this address actually requested now by my friend
* or this `0xC6838325843A665BC84ebF43377E1BA7EA4C8244` yesterday.

**Comment by wojciechka** [comment]
+1, ran into same issue some hours ago

**Comment by nikitasius** [comment]
guess due forking on ETH network.

**Comment by sponnet** [comment]
this should be solved .

**Comment by azmain84** [comment]
> Hai, tebak sesuatu yang rusak.
> 
> Saya meminta bayaran, mendapat maklum balas tetapi tidak menerima apa-apa.
> 
> * `0xee168726d52313651aee118a2b4416ece521e8cc` alamat ini sebenarnya diminta oleh rakan saya sekarang
> * atau `0xC6838325843A665BC84ebF43377E1BA7EA4C8244`hari ini .

me to
