### ISSUE TITLE
Faucet stopped working?

### ISSUE THREAD

**Issue by MatthiasLohr** [sponnet/locals-faucetserver#15]
Hello,

since 11 days, the faucet does not seem to be working anymore. The last outgoing transaction of `0x687422eea2cb73b5d3e242ba5456b782919afc85` was 11 days before. Can you please take a look? Thanks!

Best regards
Matthias

**Comment by sponnet** [comment]
The transactions still go out - I'm using infura at the moment. But they indeed do not appear on etherscan. So either etherscan is out of sync , or infura is for what I can see from here.

I'll look into it !

**Comment by sponnet** [comment]
re-started the faucet.. It seems to work now.
https://ropsten.etherscan.io/tx/0xbb100aafee02fbf1b99aff8ecb715050e2f303e2a109c04ffe48075947ff4190

If you need some Ropsten ETH now - just send me your address and I'll send some manually.

**Comment by MatthiasLohr** [comment]
Great thanks!

Some eths for `0x1Fea590b88Bbd853D38275D0254342498fe15C67` would be nice, thank you very much!

**Comment by sponnet** [comment]
https://ropsten.etherscan.io/tx/0xe93870623c84a06e9b1395fcd10cd431b872f1f476a139cebc990160b120ad8c

There you go !

**Comment by MatthiasLohr** [comment]
Wow, thanks!

**Comment by MatthiasLohr** [comment]
@sponnet, I think there's again a problem with the faucet.

**Comment by nikitasius** [comment]
yep. i confirm. no tx in sent.

**Comment by nikitasius** [comment]
btw if someone need ETH, post your addresses here, i will send you ETH

**Comment by sponnet** [comment]
I switched the ropsten endpoint to another public endpoint ( https://ropsten-rpc.linkpool.io/ ) 

Seems to work again: https://ropsten.etherscan.io/address/0x687422eea2cb73b5d3e242ba5456b782919afc85

**Comment by nikitasius** [comment]
403 Forbidden

**Comment by sponnet** [comment]
Sorry that was confusing.... The url.for the faucet is still https://faucet.ropsten.be/ , it just uses the above rpc endpoint to send its transactions..
