### ISSUE TITLE
Faucet doesn't work again

### ISSUE THREAD

**Issue by nikitasius** [sponnet/locals-faucetserver#16]
Well, eth devs are fuckedup ropsten network with Istambul work (from 2 oct). I had same shit.

Solution:
* stop geth
* download geth 1.9.6
* wipe all blockchain data (keep your wallet keys, sure)
* run fast syncing for ropsten (testnet)
* let it sync, do not touch it

During syncing you can see sick values like i had https://github.com/ethereum/go-ethereum/issues/20162

If you use non-secure environment (due it's testnet), new geth will allow you to unlock wallets if you run it with `--allow-insecure-unlock` key.

P.S. if someone want ETH, write your address here.

**Comment by ligi** [comment]
what faucet are you referring to?

**Comment by sfitzjava** [comment]
If you are sending  Eth from testnet here is my address 
0x799570c5D9D60E58D124f6c5AC5D3b369C943c43

**Comment by sponnet** [comment]
I switched back to the Infura ropsten endpoint... seems to work again.
@sfitzjava : I added you to the queue to receive Ropsten ETH. https://ropsten.etherscan.io/tx/0x28c810564fb9ace862294ae22b5430d1b88d5ac9eea932517d40438ff0cdbd8e

**Comment by verde2020** [comment]
Hi can you add me here is my ether rop address 0xdB8aADe91C47f808CF874a66623c2aD74b18D516

**Comment by perkdas** [comment]
Hi can you add me here is my ether rop address
0x7aAd2993bDC723C95567c7BA466f5858120F350c
