### ISSUE TITLE
Faucet not working anymore ?

### ISSUE THREAD

**Issue by hhanquez** [sponnet/locals-faucetserver#17]
Hello,

The last outgoing transaction of 0x687422eea2cb73b5d3e242ba5456b782919afc85 was sent 15 days ago.
Can you have a look at it ?

Also, could you send some ethers to this address ? It would be very nice ! Thank you

Best regards
Hoël

**Comment by sponnet** [comment]
I restarted it, and it seems to be dripping eth again !

**Comment by hhanquez** [comment]
Indeed ! Thanks

Could you send some ethers to this address ? It would be very nice ! Thank you
0x7332eA1229c11C627C10eB24c1A6F77BceD1D5c1
