### ISSUE TITLE
Faucet not working

### ISSUE THREAD

**Issue by StillFantastic** [sponnet/locals-faucetserver#19]
It seems like the faucet is not making any transaction, maybe it need to be restarted?

Thanks in advance!

**Comment by Ishlah86** [comment]
$ parity — chain ropsten — bootnodes “enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303”

**Comment by sponnet** [comment]
restarted it - seems to work again (
https://ropsten.etherscan.io/tx/0x235b1dd5dd41e18adf578aba898ea825741d6fccc86e65684cb9a62be46591c2
 )
