### ISSUE TITLE
Not serving from demo?

### ISSUE THREAD

**Issue by Shadowstep33** [sponnet/locals-faucetserver#2]
Hi, I was temporarily using the demo url to faucet test Ether to my prototype DAPP but it seems to have stopped working. Thusly, I realized it's probably more fair to just set up my own faucet and I came across this repo.

Anyways, just wanted to alert you to it's down-status and also verify everything is working with this repo; not sure if the reason for the down status of the faucet is code related.

**Comment by ConcurrentHashMap** [comment]
@sponnet Can confirm the web demo is not working correctly. No test ether transaction is added to the blockchain on ropsten.

**Comment by ENiG87** [comment]
@Shadowstep33 @ConcurrentHashMap Same here
Dear locals-world-Team, please fix this asap, as you are the only provider of a testnet ether faucet i know of and mining in etherium wallet is buggy as sh**.
Thanks for your time and dedication!

**Comment by sponnet** [comment]
I'll look into it and let you guys know.

**Comment by sponnet** [comment]
faucet now has more than enough ETH nowadays to run without interruption for the foreseeable future. Happy hacking !
