### ISSUE TITLE
Fauce API returning code 200, but trxHash is invalid and never executed

### ISSUE THREAD

**Issue by nschapeler** [sponnet/locals-faucetserver#20]
Thank you so much for creating this faucet! I tried using the commandline API and got the following response:

```
<Response [200]>
{"address":"0x8b77b3d75b5c543c3ab9f947afd33d52e13ceb83","txhash":"0x3125f2d52c6189fbf1d72776fa4da29a8200f42661ce8aef1b1b25173f097e7a","amount":1000000000000000000}
```
I entered the txHash into [etherscan](https://ropsten.etherscan.io/tx/0x3125f2d52c6189fbf1d72776fa4da29a8200f42661ce8aef1b1b25173f097e7a) but unfortunately that transaction doesn't seem to exist and the address's balance doesn't change. I've tried this on two separate machines with different addresses as receivers and encounter this each time.

**Comment by jasonklein** [comment]
Seconded—thanks for running this service 🙏 

And yes, it seems that it stopped donating ETH. The last OUT transaction was almost a week ago: https://ropsten.etherscan.io/txs?a=0x687422eea2cb73b5d3e242ba5456b782919afc85&p=3.

**Comment by sponnet** [comment]
Rebooted it & seems fine now..
