### ISSUE TITLE
Need to buy ropsten eths

### ISSUE THREAD

**Issue by ArtemBernatskyy** [sponnet/locals-faucetserver#24]
Guys, contact me plz at my email (on my profile), I need to buy testnet ETHs to test staking at ropsten

**Comment by LordAthis** [comment]
Faucet's:

https://faucet.ropsten.be/

https://jacksonng.org/codetest/faucet/

https://ropsten.chain.link/

https://faucet.dimensions.network/

;)

**Comment by ArtemBernatskyy** [comment]
Gotcha (
