### ISSUE TITLE
Greylisting problem?

### ISSUE THREAD

**Issue by MatthiasLohr** [sponnet/locals-faucetserver#25]
Hi,

a collegue asked me to check if I'm able to get Ethers from the faucet, since he would get greylisted all the time. I also tried once, first time with my current IP address and first time in general for this year and I also got greylisted directly. Is this intented behavior or a bug?

Best regards
Matthias

**Comment by sponnet** [comment]
what is the address that you used  ?

**Comment by MatthiasLohr** [comment]
`0xCb4C7D27e47aCcAFCa27eedE2318D32b3af37F37` is my colleagues address, `0x77A2E07b4A3d54dB31f5E88475C3864A19163668` is mine.

**Comment by CrimsonGlory** [comment]
Happens the same to me. "You are greylisted for another 0 hours and 0 minutes."
0xDCaD24F8111957B18D5386de9400f9b8ea984e9A

**Comment by bentatum** [comment]
same

**Comment by CrimsonGlory** [comment]
Finally found a ropsten faucet that works:
https://www.moonborrow.com/

**Comment by sponnet** [comment]
refactored the faucet - now all requests get queued before you're added to the greylist
