### ISSUE TITLE
Can you send me eth?

### ISSUE THREAD

**Issue by pressplay21** [sponnet/locals-faucetserver#3]
I'm trying to generate huge amount of transactions for a work demo. Is it possible for you to send me 100ETHs for Ropsten test network? My address is 0xF7D48a4B5B2E25C72Cd507e5aF924A30516D753B. Thanks in advance!

**Comment by sponnet** [comment]
done https://ropsten.etherscan.io/tx/0xa2f8b78b8e1eeba43ead35fc3d8d2ab016b0de5c2293cf16818c9b746434aa77
