### ISSUE TITLE
Auto populate address from the web3

### ISSUE THREAD

**Issue by vikmeup** [sponnet/locals-faucetserver#7]
I'm using Trust Wallet(web3 browser on mobile), based on the network we present faucet to get test ether. Would it be possible to auto-populate address from `web3.accounts[0]` ?

Thanks

![simulator screen shot - iphone x - 2018-04-29 at 19 03 16](https://user-images.githubusercontent.com/1641795/39413511-1bd4142c-4be0-11e8-9a3b-e396a21cc505.png)

**Comment by sponnet** [comment]
Great idea ! I added it.  Try it out, let me know if it works. I tested with metamask and that seems to be OK. http://faucet.ropsten.be:3001/

Changes here : https://github.com/sponnet/locals-faucetserver/commit/6fce281e33553c7e90301c2bcb6c0e638894d900

**Comment by vikmeup** [comment]
@sponnet awesome! Looks great. Tested it on Trust!
